// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaEy0BdIA47oTSK6RUkIKPFbkMKx3u9A4',
    appId: '1:77433905305:web:cb915313c3cc2069bd1808',
    messagingSenderId: '77433905305',
    projectId: 'grog-app',
    authDomain: 'grog-app.firebaseapp.com',
    storageBucket: 'grog-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhhs8WZhPZAmWbN93EXujM2tYkimrxR60',
    appId: '1:77433905305:android:1d3f629b1f6a3a37bd1808',
    messagingSenderId: '77433905305',
    projectId: 'grog-app',
    storageBucket: 'grog-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr7FMIrQO5Q1fzY9Yn-wSJC0Sq-5xVlVY',
    appId: '1:77433905305:ios:102ecfd91cace2f2bd1808',
    messagingSenderId: '77433905305',
    projectId: 'grog-app',
    storageBucket: 'grog-app.appspot.com',
    iosClientId: '77433905305-ig0a5e897qj6bg535rhmb4j359tnlfaq.apps.googleusercontent.com',
    iosBundleId: 'boo.bbee.grog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr7FMIrQO5Q1fzY9Yn-wSJC0Sq-5xVlVY',
    appId: '1:77433905305:ios:bfe59e46f22abf32bd1808',
    messagingSenderId: '77433905305',
    projectId: 'grog-app',
    storageBucket: 'grog-app.appspot.com',
    iosClientId: '77433905305-jmub2vmk7t9k4m392ocdbd3hctip04dc.apps.googleusercontent.com',
    iosBundleId: 'dev.feichtinger.grog.RunnerTests',
  );
}
